-- Creating tables for Country Code
CREATE TABLE country_codes (
    Country_Name VARCHAR(80) NOT NULL,
    Alpha_2_Code VARCHAR(5) NOT NULL,
    Country_Code VARCHAR(5) NOT NULL,
    Numeric_code INT NOT NULL,
    ISO_3166_2 VARCHAR(30) NOT NULL,
    PRIMARY KEY (Country_Name),
    UNIQUE (Country_Code)
);

CREATE TABLE gdp_growth (
    country_name VARCHAR(80),
    country_code VARCHAR(5),
    g_2001 FLOAT NOT NULL,
    g_2002 FLOAT NOT NULL,
    g_2003 FLOAT NOT NULL,
    g_2004 FLOAT NOT NULL,
    g_2005 FLOAT NOT NULL,
    g_2006 FLOAT NOT NULL,
    g_2007 FLOAT NOT NULL,
    g_2008 FLOAT NOT NULL,
    g_2009 FLOAT NOT NULL,
    g_2010 FLOAT NOT NULL,
    g_2011 FLOAT NOT NULL,
    g_2012 FLOAT NOT NULL,
    g_2013 FLOAT NOT NULL,
    g_2014 FLOAT NOT NULL,
    g_2015 FLOAT NOT NULL,
    g_2016 FLOAT NOT NULL,
    g_2017 FLOAT NOT NULL,
    g_2018 FLOAT NOT NULL,
    g_2019 FLOAT NOT NULL,
    income_group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (Country_Code),
    PRIMARY KEY (country_name, country_code)
);

CREATE TABLE health_exp (
    Country_Name VARCHAR(48),
    Country_Code VARCHAR(3),
    h_2001 FLOAT NOT NULL,
    h_2002 FLOAT NOT NULL,
    h_2003 FLOAT NOT NULL,
    h_2004 FLOAT NOT NULL,
    h_2005 FLOAT NOT NULL,
    h_2006 FLOAT NOT NULL,
    h_2007 FLOAT NOT NULL,
    h_2008 FLOAT NOT NULL,
    h_2009 FLOAT NOT NULL,
    h_2010 FLOAT NOT NULL,
    h_2011 FLOAT NOT NULL,
    h_2012 FLOAT NOT NULL,
    h_2013 FLOAT NOT NULL,
    h_2014 FLOAT NOT NULL,
    h_2015 FLOAT NOT NULL,
    h_2016 FLOAT NOT NULL,
    h_2017 FLOAT NOT NULL,
    h_2018 FLOAT NOT NULL,
    h_2019 FLOAT NOT NULL,
    Income_Group VARCHAR(30) NOT NULL,
FOREIGN KEY (Country_Code) REFERENCES country_codes (Country_Code),
    PRIMARY KEY (Country_Name, Country_Code)
);

CREATE TABLE exports (
     country_name VARCHAR(80) NOT NULL,
     country_code VARCHAR(5) NOT NULL,
     e_2001 FLOAT NOT NULL,
     e_2002 FLOAT NOT NULL,
     e_2003 FLOAT NOT NULL,
     e_2004 FLOAT NOT NULL,
     e_2005 FLOAT NOT NULL,
     e_2006 FLOAT NOT NULL,
     e_2007 FLOAT NOT NULL,
     e_2008 FLOAT NOT NULL,
     e_2009 FLOAT NOT NULL,
     e_2010 FLOAT NOT NULL,
     e_2011 FLOAT NOT NULL,
     e_2012 FLOAT NOT NULL,
     e_2013 FLOAT NOT NULL,
     e_2014 FLOAT NOT NULL,
     e_2015 FLOAT NOT NULL,
     e_2016 FLOAT NOT NULL,
     e_2017 FLOAT NOT NULL,
     e_2018 FLOAT NOT NULL,
     e_2019 FLOAT NOT NULL,
     income_group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
     PRIMARY KEY (country_name, country_code)
 );

CREATE TABLE consumption (
    Country_Name VARCHAR(80) NOT NULL,
    Country_Code VARCHAR(5) NOT NULL,
    con_2001 FLOAT NOT NULL,
    con_2002 FLOAT NOT NULL,
    con_2003 FLOAT NOT NULL,
    con_2004 FLOAT NOT NULL,
    con_2005 FLOAT NOT NULL,
    con_2006 FLOAT NOT NULL,
    con_2007 FLOAT NOT NULL,
    con_2008 FLOAT NOT NULL,
    con_2009 FLOAT NOT NULL,
    con_2010 FLOAT NOT NULL,
    con_2011 FLOAT NOT NULL,
    con_2012 FLOAT NOT NULL,
    con_2013 FLOAT NOT NULL,
    con_2014 FLOAT NOT NULL,
    con_2015 FLOAT NOT NULL,
    con_2016 FLOAT NOT NULL,
    con_2017 FLOAT NOT NULL,
    con_2018 FLOAT NOT NULL,
    con_2019 FLOAT NOT NULL,
    Income_Group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (Country_Name, Country_Code)
);

CREATE TABLE education (
    Country_Name VARCHAR(80) NOT NULL,
    Country_Code VARCHAR(5) NOT NULL,
    edu_2001 FLOAT NOT NULL,
    edu_2002 FLOAT NOT NULL,
    edu_2003 FLOAT NOT NULL,
    edu_2004 FLOAT NOT NULL,
    edu_2005 FLOAT NOT NULL,
    edu_2006 FLOAT NOT NULL,
    edu_2007 FLOAT NOT NULL,
    edu_2008 FLOAT NOT NULL,
    edu_2009 FLOAT NOT NULL,
    edu_2010 FLOAT NOT NULL,
    edu_2011 FLOAT NOT NULL,
    edu_2012 FLOAT NOT NULL,
    edu_2013 FLOAT NOT NULL,
    edu_2014 FLOAT NOT NULL,
    edu_2015 FLOAT NOT NULL,
    edu_2016 FLOAT NOT NULL,
    edu_2017 FLOAT NOT NULL,
    edu_2018 FLOAT NOT NULL,
    edu_2019 FLOAT NOT NULL,
    Income_Group VARCHAR(40) NOT NULL,
    university_count INT NOT NULL,
    tuition VARCHAR(20) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (Country_Name, Country_Code)
);

CREATE TABLE population (
    Country_Name VARCHAR(80) NOT NULL,
    Country_Code VARCHAR(5) NOT NULL,
    p_2001 FLOAT NOT NULL,
    p_2002 FLOAT NOT NULL,
    p_2003 FLOAT NOT NULL,
    p_2004 FLOAT NOT NULL,
    p_2005 FLOAT NOT NULL,
    p_2006 FLOAT NOT NULL,
    p_2007 FLOAT NOT NULL,
    p_2008 FLOAT NOT NULL,
    p_2009 FLOAT NOT NULL,
    p_2010 FLOAT NOT NULL,
    p_2011 FLOAT NOT NULL,
    p_2012 FLOAT NOT NULL,
    p_2013 FLOAT NOT NULL,
    p_2014 FLOAT NOT NULL,
    p_2015 FLOAT NOT NULL,
    p_2016 FLOAT NOT NULL,
    p_2017 FLOAT NOT NULL,
    p_2018 FLOAT NOT NULL,
    p_2019 FLOAT NOT NULL,
    Income_Group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (Country_Name, Country_Code)
);

CREATE TABLE inflation_rates (
    country_name VARCHAR(80) NOT NULL,
    country_code VARCHAR(5) NOT NULL,
    inf_2001 FLOAT NOT NULL,
    inf_2002 FLOAT NOT NULL,
    inf_2003 FLOAT NOT NULL,
    inf_2004 FLOAT NOT NULL,
    inf_2005 FLOAT NOT NULL,
    inf_2006 FLOAT NOT NULL,
    inf_2007 FLOAT NOT NULL,
    inf_2008 FLOAT NOT NULL,
    inf_2009 FLOAT NOT NULL,
    inf_2010 FLOAT NOT NULL,
    inf_2011 FLOAT NOT NULL,
    inf_2012 FLOAT NOT NULL,
    inf_2013 FLOAT NOT NULL,
    inf_2014 FLOAT NOT NULL,
    inf_2015 FLOAT NOT NULL,
    inf_2016 FLOAT NOT NULL,
    inf_2017 FLOAT NOT NULL,
    inf_2018 FLOAT NOT NULL,
    inf_2019 FLOAT NOT NULL,
    income_group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (country_Name, country_code)
);

CREATE TABLE military_exp (
    country_name VARCHAR(80) NOT NULL,
    country_code VARCHAR(5) NOT NULL,
    mil_2001 FLOAT NOT NULL,
    mil_2002 FLOAT NOT NULL,
    mil_2003 FLOAT NOT NULL,
    mil_2004 FLOAT NOT NULL,
    mil_2005 FLOAT NOT NULL,
    mil_2006 FLOAT NOT NULL,
    mil_2007 FLOAT NOT NULL,
    mil_2008 FLOAT NOT NULL,
    mil_2009 FLOAT NOT NULL,
    mil_2010 FLOAT NOT NULL,
    mil_2011 FLOAT NOT NULL,
    mil_2012 FLOAT NOT NULL,
    mil_2013 FLOAT NOT NULL,
    mil_2014 FLOAT NOT NULL,
    mil_2015 FLOAT NOT NULL,
    mil_2016 FLOAT NOT NULL,
    mil_2017 FLOAT NOT NULL,
    mil_2018 FLOAT NOT NULL,
    mil_2019 FLOAT NOT NULL,
    income_group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (country_Name, country_code)
);

CREATE TABLE unemployment_rate (
    country_name VARCHAR(80) NOT NULL,
    country_code VARCHAR(5) NOT NULL,
    une_2001 FLOAT NOT NULL,
    une_2002 FLOAT NOT NULL,
    une_2003 FLOAT NOT NULL,
    une_2004 FLOAT NOT NULL,
    une_2005 FLOAT NOT NULL,
    une_2006 FLOAT NOT NULL,
    une_2007 FLOAT NOT NULL,
    une_2008 FLOAT NOT NULL,
    une_2009 FLOAT NOT NULL,
    une_2010 FLOAT NOT NULL,
    une_2011 FLOAT NOT NULL,
    une_2012 FLOAT NOT NULL,
    une_2013 FLOAT NOT NULL,
    une_2014 FLOAT NOT NULL,
    une_2015 FLOAT NOT NULL,
    une_2016 FLOAT NOT NULL,
    une_2017 FLOAT NOT NULL,
    une_2018 FLOAT NOT NULL,
    une_2019 FLOAT NOT NULL,
    income_group VARCHAR(40) NOT NULL,
FOREIGN KEY (country_code) REFERENCES country_codes (country_code),
    PRIMARY KEY (country_Name, country_code)
);